### PR TITLE
Redefine highlights when colorscheme changes

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by rcarriga** [comment]
Hey, could you explain the reasons for this change? I'm not sure what the point of this is

**Comment by akinsho** [comment]
@rcarriga I should leave this to the author but as I'm keen to see this change as well, Ill offer an explanation. The point I believe is that when setting highlights if they are not re-applied on the Colorscheme autocommand then they disappear since by changing colour schemes existing highlights are cleared. This means that if you reload your config or change your colorscheme this plugins highlights disappear and all notifications become white.

**Comment by lewis6991** [comment]
Basically what @akinsho has said. It is pretty common for colorschemes to run `highlight clear`, so if someone's config sets a colorscheme after setting up this plugin, the highlight may be cleared.

**Comment by rcarriga** [comment]
Ah completely forgot that, haven't changed my colorscheme in a long time :sweat_smile:

**Pull request merged**
