### PR TITLE
feat: add wrapped-default as render

### PR DESCRIPTION
**Pull request by RenatoValentim**

### CODE REVIEW

**Comment by RenatoValentim** [comment]
The wrap-default render ensures that long notification messages are displayed in a more user-friendly manner within the notification window. This prevents the message from exceeding the visible area or covering parts of the working file.
notify

**Comment by RenatoValentim** [comment]
Code sample.
```lua
local notify = require('notify')
notify.notify(
  'Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.',
  'info',
  { title = 'Lorem ipsum' }
)
```

**Comment by ernieIzde8ski** [comment]
Getting this error spam while trying to use `wrapped-default`:

image

**Comment by RenatoValentim** [comment]
Thank you for bringing this to my attention! I have now added tests to cover the scenario you provided.

**Comment by rcarriga** [comment]
Thanks for the PR!

**Pull request merged**
