### PR TITLE
feat(config): allow setting a default direction

### PR DESCRIPTION
**Pull request by akinsho**
This allows setting `config.direction` and refactors each stage to be a function which takes the direction as an argument. The direction from the config is then passed to the style that is set.

Not sure what your thoughts are re. this approach @rcarriga, if it seems alright to you then I'll add some docs for it

### CODE REVIEW

**Comment by akinsho** [comment]
This relates to https://github.com/rcarriga/nvim-notify/issues/84#issuecomment-1229204298

**Comment by rcarriga** [comment]
Thanks for the PR! I think this looks good except for that the stages don't actually implement all values for direction. I'm not sure they should either because it might make them a lot more complex trying to handle all of the conditions.

Either let's change the config option to a boolean `top_down` or something like that or you can add support to the stages if you feel it's not much difference.

**Comment by akinsho** [comment]
@rcarriga I've refactored the option to just be a boolean. Making them all work with more directions is tbh not the feature I personally was wanting, just seemed like an added bonus but ultimately all I want is for notifications to appear on the bottom.

**Comment by rcarriga** [comment]
Thanks again!

**Comment by Alex-vZyl** [comment]
Nice!

**Pull request merged**
